application: getkeycode
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /resource
  static_dir: resource

- url: .*
  script: main.php

# Serve php scripts.
- url: /(.+\.php)$
  script: \1